version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6

    working_directory: ~/twitter-sentiment

    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "requirements.txt" }}
          - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            python3 -m venv twitter_sentiment
            . twitter_sentiment/bin/activate
            pip install -r requirements.txt

      - save_cache:
          paths:
            - ./twitter_sentiment
          key: v1-dependencies-{{ checksum "requirements.txt" }}

      - run:
          name: run twitter_sentiment tests
          command: |
            . twitter_sentiment/bin/activate
            cd test/
            python3 -m unittest test_twitterSentiment

      - store_artifacts:
          path: test-reports
          destination: test-reports

  deploy:
    docker:
      - image: circleci/python:3.6
    steps:
      - checkout

      - restore_cache:
          key: v1-dependencies-{{ checksum "requirements.txt" }}

      - run:
          name: verify git tag vs version
          command: |
            python3 -m venv twitter_sentiment
            . twitter_sentiment/bin/activate
            python3 setup.py verify

      - save_cache:
          paths: 
            - ./twitter_sentiment
          key: v1-dependencies-{{ checksum "requirements.txt" }}

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/

      - deploy:
          requires:
            - build
          filters:
            tags:
              only: /[0-9]+(\.[0-9]+)*/
            branches:
              ignore: /.*/


          



